//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceRoutingSoap")]
    public interface IServiceRoutingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingSoap/getClosestStation", ReplyAction="http://tempuri.org/IServiceRoutingSoap/getClosestStationResponse")]
        System.Threading.Tasks.Task<float[]> getClosestStationAsync(float x, float y, bool isArrival);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingSoap/getWalkingPath", ReplyAction="http://tempuri.org/IServiceRoutingSoap/getWalkingPathResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getWalkingPathAsync(string lat1, string long1, string lat2, string long2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingSoap/getCyclingPath", ReplyAction="http://tempuri.org/IServiceRoutingSoap/getCyclingPathResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getCyclingPathAsync(string lat1, string long1, string lat2, string long2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceRoutingSoapChannel : ServiceReference1.IServiceRoutingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceRoutingSoapClient : System.ServiceModel.ClientBase<ServiceReference1.IServiceRoutingSoap>, ServiceReference1.IServiceRoutingSoap
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceRoutingSoapClient() : 
                base(ServiceRoutingSoapClient.GetDefaultBinding(), ServiceRoutingSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceRoutingSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRoutingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceRoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceRoutingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRoutingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceRoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRoutingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceRoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceRoutingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<float[]> getClosestStationAsync(float x, float y, bool isArrival)
        {
            return base.Channel.getClosestStationAsync(x, y, isArrival);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getWalkingPathAsync(string lat1, string long1, string lat2, string long2)
        {
            return base.Channel.getWalkingPathAsync(lat1, long1, lat2, long2);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getCyclingPathAsync(string lat1, string long1, string lat2, string long2)
        {
            return base.Channel.getCyclingPathAsync(lat1, long1, lat2, long2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceRoutingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceRoutingSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8735/Design_Time_Addresses/RoutingService/ServiceSoap/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceRoutingSoapClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceRoutingSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceRoutingSoapClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceRoutingSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceRoutingSoap,
        }
    }
}
